logging:
  level:
    # Enable all logging for app
    me.vrublevsky.neotech.domains: DEBUG
    # Enable request & response logging for integration tests
    feign: DEBUG

app:
  integrations:
    whois:
      whoisxmlapi:
        debug: true # Enable detailed logging (including network requests)
        url: http://localhost:10020 # Points to locally started mock server (see IntegrationTest)
        api-key: test-api-key
    registrar:
      namecheap:
        enabled: true
        debug: true
        url: https://api.sandbox.namecheap.com/xml.response
        api-key: 43938e4b41b84eceb953c74cebf44fa2
        api-user: FylmTM
        api-username: FylmTM
        api-client-ip: 95.68.90.78
