logging:
  level:
    # Enable all logging for app
    me.vrublevsky.neotech.domains: DEBUG
    # Enable request & response logging for integration tests
    feign: DEBUG

app:
  integrations:
    whois:
      whoisxmlapi:
        debug: true # Enable detailed logging (including network requests)
        url: http://localhost:10020 # Points to locally started mock server (see IntegrationTest)
        api-key: test-api-key
    registrar:
      namecheap:
        debug: true # Enable detailed logging (including network requests)
        url: http://localhost:10021 # Points to locally started mock server (see IntegrationTest)
        api-key: test-api-key
        api-user: user
        api-username: username
        api-client-ip: 127.0.0.1
